version: "3.8"

services:
  database:
    image: postgres:15-bullseye
    container_name: database_service
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    expose:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - db_network
    volumes:
      - pgsql-db-data:/var/lib/postgresql/data

  server:
    container_name: server
    image: server
    hostname: server
    restart: always
    command: yarn dev
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}"
    tty: true
    networks:
      - db_network
    depends_on:
      - database

networks:
  db_network:
    driver: bridge

volumes:
  pgsql-db-data:
    driver: local
