version: "3.8"

services:
  db:
    image: postgres:15-bullseye
    restart: on-failure
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: indie_app
    ports:
      - 5432:5432
    networks:
      - database
    volumes:
      - pgsql-db-data:/var/lib/postgresql/data

networks:
  database:

volumes:
  pgsql-db-data:
    driver: local