version: "3.8"

services:
  database:
    container_name: database
    image: postgres:15-bullseye
    restart: on-failure
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: indie_app
    ports:
      - 5432:5432
    networks:
      - database
    volumes:
      - pgsql-db-data:/var/lib/postgresql/data
  server:
    container_name: server
    image: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}"
    tty: true
    networks:
      - database

networks:
  database:

volumes:
  pgsql-db-data:
    driver: local
